// Code generated by MockGen. DO NOT EDIT.
// Source: internal/OrderProducts/usecase.go

// Package mock_orderProducts is a generated GoMock package.
package mock_orderProducts

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	OrderProducts "github.com/rinatkh/test_2022/internal/OrderProducts"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// AddOrderProducts mocks base method.
func (m *MockUseCase) AddOrderProducts(params *OrderProducts.AddOrderProductsRequest) (*OrderProducts.AddOrderProductsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrderProducts", params)
	ret0, _ := ret[0].(*OrderProducts.AddOrderProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrderProducts indicates an expected call of AddOrderProducts.
func (mr *MockUseCaseMockRecorder) AddOrderProducts(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrderProducts", reflect.TypeOf((*MockUseCase)(nil).AddOrderProducts), params)
}

// DeleteOrderProducts mocks base method.
func (m *MockUseCase) DeleteOrderProducts(params *OrderProducts.DeleteOrderProductsRequest) (*OrderProducts.DeleteOrderProductsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderProducts", params)
	ret0, _ := ret[0].(*OrderProducts.DeleteOrderProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOrderProducts indicates an expected call of DeleteOrderProducts.
func (mr *MockUseCaseMockRecorder) DeleteOrderProducts(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderProducts", reflect.TypeOf((*MockUseCase)(nil).DeleteOrderProducts), params)
}

// GetOrderProducts mocks base method.
func (m *MockUseCase) GetOrderProducts(params *OrderProducts.GetOrderProductsRequest) (*OrderProducts.GetOrderProductsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderProducts", params)
	ret0, _ := ret[0].(*OrderProducts.GetOrderProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderProducts indicates an expected call of GetOrderProducts.
func (mr *MockUseCaseMockRecorder) GetOrderProducts(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderProducts", reflect.TypeOf((*MockUseCase)(nil).GetOrderProducts), params)
}
