// Code generated by MockGen. DO NOT EDIT.
// Source: internal/currency/usecase.go

// Package mock_currency is a generated GoMock package.
package mock_currency

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	currency "github.com/rinatkh/test_2022/internal/currency"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetCurrency mocks base method.
func (m *MockUseCase) GetCurrency(params *currency.GetCurrencyRequest) (*currency.GetCurrencyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrency", params)
	ret0, _ := ret[0].(*currency.GetCurrencyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrency indicates an expected call of GetCurrency.
func (mr *MockUseCaseMockRecorder) GetCurrency(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrency", reflect.TypeOf((*MockUseCase)(nil).GetCurrency), params)
}
